This resolves an issue in development mode where the reloading of classes would cause the reloading errors.
    ArgumentError: A copy of <Some Class Here> has been removed from the module tree but is still active!

This was because we were keeping a class reference within scope. To resolve this only store the name and re-constantize when the time is necessary to pass along the event notification.